INSERT INTO products (id, title, marca, fk_id_petType, image, price, description, fk_id_category, color, size) VALUES 
(41, 'Mueble Tipo Torre con Rampa', 'EveryYay', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wzNTc1N3xpbWFnZS9qcGVnfGltYWdlcy9oNmIvaGU3Lzk1MzgzNjY3MzQzNjYuanBnfGMxNWVhY2E1ODBmMzUzOGMyMTc5NWVjZDQ1MGUwOTcwOWM0NzVjZTVjNjQ5OTRiODM1MTk1ZjZjNDc4Mjk2MTQ', '$1,079.40', 'Mueble para Gatito Tipo Torre con Rampa.', 4, 'Gris', 'NA'),
(42, 'Mueble Tipo Torre Con Guarida y Repisa', 'EveryYay', 2, 'https://www.petco.com.mx/medias/300ftw-142229.jpg?context=bWFzdGVyfHJvb3R8MzQ4Mjd8aW1hZ2UvanBlZ3xoMjEvaGZhLzEwNjA2NjE1NzU2ODMwLzMwMGZ0d18xNDIyMjkuanBnfGUxZmI4YzBkOTEzYmFhZTc3OWJjNTlmNDVmYTU1MmQ3OTA3YmY5N2VkZjIzYWU1MjM3ZjJlMWI4MzRkZDQ0NGQ', '$1,679.40', 'Mueble Tipo Torre con Guarida y Repisa para Gato, Beige.', 4, 'Beige', 'NA'),
(43, 'Alberca de Pelotas para Juegos', 'Marshall', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyNDE5MXxpbWFnZS9qcGVnfGltYWdlcy9oYTQvaDI2Lzk1MjkxNTczNTM1MDIuanBnfDFlNmYwOGZhMzU5YjJhNTU5NWM1ZGY5ZWIxMDJkNTJkY2FmYzMyZWQ2NTQyYjA0NGM3OGI2YTZlMGU5YWUzMjM', '$775.00', 'Marshall Alberca de Pelotas para Juegos Pop-n-Play.', 4, 'NA', 'NA'),
(44, 'Chew Esferas de Sauce', 'You & Me', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w2MTA4OXxpbWFnZS9qcGVnfGltYWdlcy9oZTQvaDIzLzkyMDEzNTU4MTY5OTAuanBnfGQyMjBmNWQ5MGY3ZmI5NjI4OTI1ZDJlMWQxNmI5MzEyZGYzMWYxOWI2MjcyYzhiZWNiYzcyNTFhNDQ1ZmMyODk', '$123.50', 'You & Me Chew Esferas de Sauce, 3 Piezas.', 4, 'NA', 'NA'),
(45, 'Bolas Rodadoras para Pequeñas Mascotas', 'Oxbow', 3, 'https://www.petco.com.mx/medias/133191.jpg-300ftw?context=bWFzdGVyfHJvb3R8NjI5MTV8aW1hZ2UvanBlZ3xoYjcvaDVmLzk1NzU1MzcwNDk2MzAuanBnfDcxYTU3NmQ0Y2U4MzA2NjFiZGJmMGFlYTg5ODY0OTliZDJlNzFjOGU5YzJmMzRkYTVjZThlNTkxODYwZTMyNTA', '$161.50', 'Oxbow Enriched Life Bolas Rodadoras para Pequeñas Mascotas.', 4, 'NA', 'NA'),
(46, 'Escondite Castillo', 'You & Me', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w0ODA3OXxpbWFnZS9qcGVnfGltYWdlcy9oZTIvaDQxLzkyMDEzMTk1NDI4MTQuanBnfDFlYzY0ODljZjVlMzU4ZWJhMjNiNWYxYmQxMDk5OTlmYzc3YjdjZDJkOWM0NDA1YjExODZhMGExZDIzN2ZlOTQ', '$145.00', 'You & Me Escondite Castillo, Mediano.', 4, 'NA', 'NA'),
(47, 'Túnel', 'Ware', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1MjI5MHxpbWFnZS9naWZ8aW1hZ2VzL2gwMy9oNGQvODg0ODEwMzU3MTQ4Ni5naWZ8MjYyMjhiMjJkY2U4ODY3ZTA0NjI1ZGY0YzU4N2MzMGQ2ZWE5YjVjMGZkNWQ3YzY4NzMzNzMyNzc0ODE2NzI1Nw', '$289.75', 'Ware Túnel, XX-Grande.', 4, 'NA', 'NA'),
(48, 'Microchip Para Mascotas Perros y Gatos', 'Chip Mascotas', 1, 'https://m.media-amazon.com/images/I/61RcC5iGZML._AC_SL1200_.jpg', '$850.75', '1x Microchip de 7mm con aplicador, 1 Pasaporte para mascotas, 1 Placa inteligente NFC & QR, 1 Certificado QR/Nfc, 4 Tarjetas de Identificación de microchip, 6 Etiquetas con el número del microchip, 1 Registro de microchip en plataforma de por vida.', 5, 'NA', 'NA'),
(49, 'Bebedero Mason', 'Stokes Wildbird', 4, 'https://www.petco.com.mx/medias/125017.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDE4NjJ8aW1hZ2UvanBlZ3xoMmEvaGM1LzEwNTI3ODg5MTk1MDM4LzEyNTAxNy5qcGdfMzAwZnR3fDIwNzdlNjIwNjI2MGY1NmJkMTBlMGJkYTViMmJiY2E4Njg0MzJjNDIwNjdmNmNhMDVlOGJjNzJmZTcwMGFmZTQ', '$669.00', 'Un bebedero encantador con un diseño clásico de Mason Jar, perfecto para atraer colibríes.', 1, 'NA', 'NA'),
(50, 'Bebedero Amatista', 'Stokes Wildbird', 4, 'https://www.petco.com.mx/medias/125016.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzY3ODV8aW1hZ2UvanBlZ3xoNTgvaDA5LzEwNTI3ODg3ODg0MzE4LzEyNTAxNi5qcGdfMzAwZnR3fGRiYWJmNjZmNDcwMjk1YjJiNzIwN2M4MjE4MDJkOTg0MjI1ZWVmYzNkMmY1OGVlYjdjZDNmZjhjY2FhYWIwYTE', '$679.00', 'Bebedero de color amatista, atractivo y diseñado específicamente para colibríes.', 1, 'Amatista', 'NA');





























(81, 'Bird Banquet Original Formula Hueso de Jibia para Aves', 'Zoo Med',4,'https://www.petco.com.mx/medias/300ftw-130687.jpg?context=bWFzdGVyfHJvb3R8ODkyNzl8aW1hZ2UvanBlZ3xoNDMvaGJmLzEwODA0MzY3ODE4NzgyLzMwMGZ0d18xMzA2ODcuanBnfDUyMTM5YjZkMjQ0MTRiZmQ3ODkzNWE4MWE5NDk2OTRlZmMxNjFiN2U5YmZkOTU1NjEwYzFmNTkwYjgyNjExZGM', '$46.55',' Este producto de 28.34g es ideal para aves, proporcionando calcio y minerales esenciales para su salud.',' Medicamentos',' NA', '28.34g'),
(82, 'Bird Banquet Fruit Formula Hueso de Jibia con Fruta para Aves', 'Zoo Med', 4, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMTA2MjR8aW1hZ2UvanBlZ3xpbWFnZXMvaGQzL2g2MC85NDAwMDk3MzQxNDcwLmpwZ3xkM2Q4YjUxMDFhNDJhMGZhMDQwYWU1NWMzOGYwZWU3MjA0NmEzNGEyYTQyM2E2MTdiMDI3ZDFkNjE2MWE4Yjk1', '$46.55', 'Este complemento está diseñado para promover la salud de las aves con una mezcla sabrosa de jibia y frutas, aportando nutrientes esenciales.', 'Medicamentos', 'NA', '28.34g'),
(83, 'Bird Banquet Mealworm Formula Hueso de Jibia con Gusano de Harina para Aves', 'Zoo Med', 4, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMTMyNTl8aW1hZ2UvanBlZ3xpbWFnZXMvaDllL2hhMS85NDAwMDk3NzAxOTE4LmpwZ3xkMzRkOWJmZDBhY2RhZjYxOGNiODk0MmEyNmYxNDg1OWNiMDhmZTRkZDE1NDc5NDkzODdjNzViYzEwYjU0NjA4', '$46.55', 'Ideal para aves que disfrutan de una dieta rica en proteínas, este producto combina jibia con gusanos de harina para una nutrición completa.', 'Medicamentos', 'NA', '28.34g'),
(84, 'Bird Banquet Vegetable Formula Hueso de Jibia con Vegetales para Aves', 'Zoo Med', 4, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMTIyODJ8aW1hZ2UvanBlZ3xpbWFnZXMvaGZiL2hhYy85NDAwMDk4NDg4MzUwLmpwZ3w3NzQxN2RmZmFmNjM1YTU4OGQ5ZjBkMTRjMzA5Njg2ZjkwZDIwNWVmODMwZmFkMTFkYTNiMDE3MjJiZjc0NWQ3', '$46.55', 'Esta fórmula mezcla jibia con una variedad de vegetales, ofreciendo una opción saludable y deliciosa para tus aves.', 'Medicamentos', 'NA', '28.34g'),
(85, 'Bloque Mineral para Ave', 'Zoo Med', 'Aves', 'https://www.petco.com.mx/medias/300ftw-142128.jpg?context=bWFzdGVyfHJvb3R8MjM2NjN8aW1hZ2UvanBlZ3xoNDgvaDhiLzEwNjA3MTMyMjQ2MDQ2LzMwMGZ0d18xNDIxMjguanBnfDIxNTQ2ODhhYjFmMmY4MjkwYWM0ZTRlNDU4OWRmMDhhMTBlMDNiNjlhNGY4YjdkYjJmNWI1OWYwMjczZDgwZWM', '$169.00', 'Bloque mineral grande para aves, que aporta calcio y minerales esenciales para una dieta equilibrada. Ideal para aves de tamaño grande.', 'Medicamentos', 'NA', 'Grande'),
(86, 'Mezcla de Heno Pasto Timothy y Pasto de Orchard para Roedores', 'Oxbow', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMDc0Nzh8aW1hZ2UvanBlZ3xpbWFnZXMvaDk5L2g2Zi85NDEyNDU5NTYwOTkwLmpwZ3w3YWQ0MWE5NDg2YzBjOWY0MDI1MTI4ZjlkZjBiZjM0MmQ4MmYwMzU1MjJiZDEyMDg0ZTNkMzFkYmExM2Q2YjFh', '$332.50', 'Ideal para roedores de todas las edades, proporcionando una mezcla nutritiva y rica en fibra.', 'Alimento', 'NA', '1.1kg'),
(87, 'Premium Alimento para Conejo Adulto', 'Cunipic', 3, 'https://www.petco.com.mx/medias/300ftw-114755.jpg?context=bWFzdGVyfHJvb3R8NjcwOTF8aW1hZ2UvanBlZ3xoYTIvaGY1LzEwNjQ2MTIxNzA5NTk4LzMwMGZ0d18xMTQ3NTUuanBnfGNmN2EyMjY5YzY1ZGY5NmZkNDNkMTAzNWU5ZGZmODFhOWVlOTIxMjFmZGEyMjFmMTZiZDZhNmY4OTU0Y2E2NjM', '$463.25', 'Formula especial para satisfacer las necesidades nutricionales de los conejos adultos, promoviendo su salud general.', 'Alimento', 'NA', '5kg'),
(88, 'Western Pasto Timothy para Roedores Todas las Edades', 'Oxbow', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMDk5MjV8aW1hZ2UvanBlZ3xpbWFnZXMvaGQ3L2hjYS85NDAwMDk4NDg4MzUwLmpwZ3w5Yzg1MmMxMTc3ZjIyMWVhNzg4ZjBjMmJlNjY4OTQ5ZDczZjQ2YzgxYTkwNmIwZWE2MWRiNTM5ZDAzMTdlYWFi', '$332.50', 'Este heno es una fuente rica en fibra que favorece una digestión saludable.', 'Alimento', 'NA', '1.1kg'),
(89, 'Alpha Pro Alimento Completo para Conejo Adulto', 'Cunipic', 3, 'https://www.petco.com.mx/medias/300ftw-126546.jpg?context=bWFzdGVyfHJvb3R8NzE2MzF8aW1hZ2UvanBlZ3xoMzYvaDAzLzEwNzMzNjU1MTMwMTQyLzMwMGZ0d18xMjY1NDYuanBnfGI2NzkwOThhNTM0MjlmODM5NmViY2I3MDNjNDI3NDlhNDg5OTg1YWM2Mzg2MTMwZjZlM2I1ZDEzMjMwNjkwNGQ', '$437.75', 'Alimento completo y equilibrado para conejos adultos. Rico en fibra, favorece la digestión y la salud dental.', 'Alimento', 'NA', '1.7kg'),
(90, 'Essentials Alimento Seco para Conejo Adulto', 'Oxbow',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMDA2MjN8aW1hZ2UvanBlZ3xpbWFnZXMvaGJlL2g0NC85NDAwMTA1NTk5MDA2LmpwZ3w5OWZiNTJkM2JhODllYWIyNTA3MzNmNzRjNjM4MDAwM2I4NDIxMGU1ZjQzNmY0ZjY3ZDA0NGRiNjUxODI2YWNh', '$361.00', 'Alimento seco de alta calidad para conejos adultos. Promueve la salud digestiva y dental con ingredientes naturales.', 'Alimento', 'NA', '2.25kg'),
(91, 'Alimento Seco para Conejo Enano Adulto', 'Versele-Laga',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1NTY4N3xpbWFnZS9qcGVnfGltYWdlcy9oMmUvaDc3Lzk0NTc0NDk0MzUxNjYuanBnfGExYzg0NDA4NjRkMGMzNTJmOTZkMzJlY2U0Nzk5MjhiOGZkNzMzZWRlZTI0NDI0NDNmODQ2OTEzNmI2ZGM4MTQ', '$503.50', 'Alimento completo para conejos enanos adultos. Favorece la digestión y la salud del pelaje con ingredientes naturales.', 'Alimento', 'NA', '1.7kg'),
(92, 'Premium Alimento para Conejo Junior', 'Cunipic',3, 'https://www.petco.com.mx/medias/300ftw-114701.jpg?context=bWFzdGVyfHJvb3R8NjQ5MTB8aW1hZ2UvanBlZ3xoMmMvaGUwLzEwNjQ2MTE4NzYwNDc4LzMwMGZ0d18xMTQ3MDEuanBnfDU5YjlmYTYxZmYyMDRjNTEzZTMyODEyZTJiODcyNDhmZmNmOGRiMDQ4OWQ5MTgzMWU1ODM3ZWY5ODg1NjYwMDM', '$284.75', 'Alimento premium para conejos jóvenes. Nutrición balanceada con vitaminas esenciales para un crecimiento saludable.', 'Alimento', 'NA', '2.5kg'),
(93, 'Western Pasto Timothy para Roedores Todas las Edades', 'Oxbow',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w5NjU1MnxpbWFnZS9qcGVnfGltYWdlcy9oYTkvaDg5Lzk0MTI0NTM5NTc2NjIuanBnfGFiOWRmYWIwOTIzM2FkZDIwMDNhMjViZGM3MWE5MzU2MDExZGQ0MDBiMDI0MjA0ZWU2MTQ5ZDAzMTU2NzE2MjI', '$175.75', 'Pasto Timothy natural para roedores de todas las edades. Rico en fibra, favorece la digestión y el desgaste dental.', 'Alimento', 'NA', '425g'),
(94, 'Alimento Alpha Pro Light para Conejo Adulto', 'Cunipic',3, 'https://www.petco.com.mx/medias/135134.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDExMzJ8aW1hZ2UvanBlZ3xoYjUvaGNjLzk5NjE4NTIyMDcxMzQvMTM1MTM0LmpwZ18zMDBmdHd8N2E3NmMxZjIwMzVjZGIwNTBlNzA1ZTNjNzlkOGM0MWRiYjNiZDcyODM0NTBhMzY4OGYyMDczYjc1ODNmZGIwNw', '$433.50', 'Alimento light para conejos adultos. Bajo en calorías y alto en fibra para un peso saludable.', 'Alimento', 'NA', '1.7kg'),
(95, 'Alimento Garden Select para Conejo Adulto', 'Oxbow',3, 'https://www.petco.com.mx/medias/136394.jpg-300ftw?context=bWFzdGVyfHJvb3R8MjMyNDZ8aW1hZ2UvanBlZ3xoYTQvaGQyLzEwMzc0MzIxNTA0Mjg2LzEzNjM5NC5qcGdfMzAwZnR3fDZmZDI4OGRkODNjZTQ3ZDU1MjIzYzcxZDcxYjcyZWQ1YzIwNGE1YTUzYTAwYjUwNzkwYTQ1YmIwNmRiYjFlZmY', '$418.00', 'Alimento natural para conejos adultos. Con ingredientes seleccionados que promueven una salud óptima.', 'Alimento', 'NA', '1.8kg');
(96, 'Kit de Grooming', 'Ware',3, 'https://www.petco.com.mx/medias/300ftw-102448.jpg?context=bWFzdGVyfHJvb3R8Nzg0NDV8aW1hZ2UvanBlZ3xoNjMvaDNmLzEwNjQxNzU4NTg0ODYyLzMwMGZ0d18xMDI0NDguanBnfGU4NjUxZGIzNTMwNTg5OGY4OThlOTYyNWFhNGVhMGM2ZWY2MDQ5MDZlYWI4YWIzODUzZDI5YWJjMTAyNzViZTU', '$251.75', 'Mantén a tu conejo siempre impecable con este completo kit de grooming.', 'Accesorios', 'NA', 'NA'),
(97, 'Limpiador Hábitat para Mamíferos', 'Sophresh',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wzNDU3NHxpbWFnZS9qcGVnfGltYWdlcy9oMmQvaDI5LzkyNTg2MjkwNzA4NzguanBnfDEzNTA3NWJhYjI5OGY0NzZjMzQ0N2IwMDE0NmM2YmY5ZTBhOTYxMjU0NWQ2Y2RhZTZkODA1ODZiY2U2MDZmMjk', '$144.00', 'Limpia y refresca el hábitat de tu conejo con este limpiador de hábitats.', 'Medicamentos', 'NA', '473 ml'),
(98, 'Animal Mineral Block Hueso de Jibia para Roedores', 'Zoo Med',3, 'https://www.petco.com.mx/medias/300ftw-130683.jpg?context=bWFzdGVyfHJvb3R8OTc0ODl8aW1hZ2UvanBlZ3xoZTgvaGE3LzEwODA0MzY3MTYzNDIyLzMwMGZ0d18xMzA2ODMuanBnfGViODg3OWExOWZmMTAxNzVkYmQwZjM3ZjU1ZDU0YWFiNjFjNGQzOWRlZjBjNzI1MzJhOWMzMGJmNjBkMGJlYmY', '$46.55', 'Dale a tu roedor un suplemento esencial con este bloque mineral de jibia.', 'Medicamentos', 'NA', '24 g'),
(99, 'Escondite Tejido', 'Oxbow',3, 'https://www.petco.com.mx/medias/133204.jpg-300ftw?context=bWFzdGVyfHJvb3R8NTc1NjV8aW1hZ2UvanBlZ3xoNWUvaDE3Lzk1NzU1NTIyNTM5ODIuanBnfGY1ZmQ2MzEzZmM4MzZiMzdiMDNkNjlkOTZmYWE2M2RjN2Y3NzljOWU0YjU3NzJmMDI1ZGU4MjM5OWIwZmVkMWI', '$555.00', 'Un escondite perfecto para tu conejo, donde puede sentirse seguro y relajado', 'Accesorios', 'NA', 'Mediano'),
(100, 'Plato Cerámica para Pequeños Mamíferos', 'Yolcame',3, 'https://www.petco.com.mx/medias/138842.jpg-300ftw?context=bWFzdGVyfHJvb3R8MTE4NzV8aW1hZ2UvanBlZ3xoMTYvaDRjLzEwMzEwNDY1NzgxNzkwLzEzODg0Mi5qcGdfMzAwZnR3fDhmNDNmYWVmOWY2NGYyMGIwZjA3OTUzOGU2YTM4Y2UwNDNhNGQwNDgyMWU2NWFhY2ZlOTdjZDdmYzc1NjNmNmI', '$120.00', 'Un plato elegante y resistente para las comidas de tu pequeño amigo peludo.', 'Accesorios', 'NA', 'Grande'),
(101, 'Bowl para Alimentación Lenta', 'Oxbow',3, 'https://www.petco.com.mx/medias/133202.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzkyNTB8aW1hZ2UvanBlZ3xoNjMvaDY3Lzk1NzU1NDk1MDE0NzAuanBnfDFhMTYxN2Y3YjBkN2UyNDdkNDY0OWZlM2RiOWVmZGZmN2JjNDQzMTE4MDNhMDNiMjIyZTU5ODMzZDMzMWY5N2E', '$280.00', 'Un comedero diseñado para que tu conejo coma más despacio y disfrute cada bocado.', 'Accesorios', 'NA', 'Chico'),
(102, 'Pala para Pequeñas Mascotas', 'Sophresh',3, 'https://www.petco.com.mx/medias/138943.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzU3NTh8aW1hZ2UvanBlZ3xoZTMvaDdiLzEwMDc0MDU4NDU3MTE4LzEzODk0My5qcGdfMzAwZnR3fDBlNjNmY2UzNmVjYjEwYmMzYmJlY2U0ZmJkOGNlOTA3NGVmYTk0MjAzMWFkOTJiZTI5NjMxYjM2NzIwNGRiZDc', '$50.00', 'La herramienta ideal para mantener la jaula de tu mascota limpia y ordenada.', 'Accesorios', 'NA', 'NA'),
(103, 'Bebedero a Prueba de Mordidas', 'Kaytee',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxNzAyOHxpbWFnZS9naWZ8aW1hZ2VzL2hkNy9oYTQvODg0ODE1NDI5NjM1MC5naWZ8M2IxMzc5NzBhYTY3MTUyMjlmYTIzNWI2Njk5Mzc3NmJlOWY2NjliYmE1YmY5Mjg1ZWYxOWE5MmFjZjg4MjVkYw', '$259.00', 'Un bebedero duradero y resistente, perfecto para evitar mordidas y fugas.', 'Accesorios', 'NA', '355 ml'),
(104, 'Dispensador de Heno', 'Kaytee',3, 'https://www.petco.com.mx/medias/300ftw-102112.jpg?context=bWFzdGVyfHJvb3R8NzA3OTJ8aW1hZ2UvanBlZ3xoODQvaGJkLzEwODMzMTE5NTEwNTU4LzMwMGZ0d18xMDIxMTIuanBnfGZiNTk5NDgwNzVlNWZmMmM0MjJhOGRmOGUxODBhMjE5ODQ2MzEyMGM0OWIxMzdkODkzNmVkOGE3NmZjY2M5Yjg', '$329.00', 'Mantén el heno fresco y accesible para tu conejo con este práctico dispensador.', 'Accesorios', 'NA', 'NA'),
(105, 'Mueble para Gato Tipo Árbol de 7 Niveles', 'You & Me',2, 'https://www.petco.com.mx/medias/300ftw-110717.jpg?context=bWFzdGVyfHJvb3R8MzQzNjl8aW1hZ2UvanBlZ3xoM2YvaDU0LzEwNjExMDU3MDAwNDc4LzMwMGZ0d18xMTA3MTcuanBnfGY0YWNkYjZjYzg4ODBkM2M2MTc2YWVlOWM3MmMwODExMTJmYzZiZDkxYWE4MmU4OTZkZjUxODgyYWM5NTZhZjU', '$2,699.25', 'Un árbol para gatos con múltiples texturas que mantendrá a tu felino entretenido y feliz.', 'Accesorios', 'NA', 'NA')
(106, 'Mueble Tipo Árbol Deluxe Ultra Resistente', 'You & Me',2, 'https://www.petco.com.mx/medias/300ftw-128164.jpg?context=bWFzdGVyfHJvb3R8MjgyNjR8aW1hZ2UvanBlZ3xoMTAvaDgyLzEwNjA2NDI1NTcxMzU4LzMwMGZ0d18xMjgxNjQuanBnfDc4NTZkZGY1MDE0MjhmZTFhYmQ1ZWJiNmI0YzhmODE1NWY1OTEyMmYzOTYyNzk4MGM2YzhiNjQ5OWFmMzEyNTM', '$3,299.25', 'Un árbol para gatos de lujo, con 7 niveles que harán que tu felino se sienta en el paraíso. ¡Ideal para trepar y explorar!', 'Accesorios', 'NA', 'NA'),
(107, 'Mueble para Gatos Senior y de Talla Grande', 'EveryYay',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wzNDEzNHxpbWFnZS9qcGVnfGltYWdlcy9oYTIvaDJhLzk1MzUxMDQ1ODE2NjIuanBnfDY1ZmJjMmQxMWE0NDc1MTZlOWMzYjQyODZkYzA2YmU0Yjc5NmM4ZjBiMDUzNzA2Mjk4MjE5NGI4ZTQxM2EwNDQ', '$2,474.25', 'Perfecto para gatos mayores y grandes, este árbol con rampa y escondite proporciona comodidad y diversión.', 'Accesorios', 'NA', 'NA'),
(108, 'Cama Tipo Cueva con Orejitas y Cola', 'Harmony',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1OTAzNXxpbWFnZS9qcGVnfGltYWdlcy9oYjMvaDg3Lzk1NDI5NTk3MjY2MjIuanBnfDk2OGZjNjQxYmU4YzI1MWQwOTVjMGQwZWNkMDJiMWI2MTgzMjBlNzhjZGYzMDBiODBhYTNiNzIzZjJlNWE3ZmE', '$399.20', 'Una cueva acogedora con orejitas y cola que mantendrá a tu gato calentito y seguro. ¡Demasiado adorable para resistir!', 'Accesorios', 'Gris', 'NA'),
(109, 'Rascador de Cartón en Forma de Sofá', 'EveryYay',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1MDM1MXxpbWFnZS9qcGVnfGltYWdlcy9oMjYvaDZlLzk1MzUwODM4Mzk1MTguanBnfGUxYWZjODUwNDY3ODYwYjVlMmU5NDkzOTIxYmNjNjYzYzZlZGY1MDRkNjNlZGFmMjcwOTliYTZkMWIzZTFjMmQ', '$336.75', 'Un rascador elegante en forma de sofá que incluye catnip para atraer a tu gato. ¡Diversión y estilo en uno!', 'Accesorios', 'NA', 'NA'),
(110, 'Cama Tipo Cueva', 'Harmony',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1NzE4MnxpbWFnZS9qcGVnfGltYWdlcy9oNmUvaDc4Lzk1NDI5NTkzNjYxNzQuanBnfDcwMWY4ZTlkNjQwZTUyNDUxODRhMzI4YzE0M2YyODg2NDBmYmI5NGNhZTAyNTg2YjhkMWNjZmM5OThjYTI3NDQ', '$399.20', 'Una cama tipo cueva en color gris, perfecta para que tu gato se acurruque y descanse cómodamente.', 'Accesorios', 'Gris', 'NA'),
(111, 'Mueble para Gato Tipo Árbol Rascacielo', 'You & Me',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w3MTU1MXxpbWFnZS9qcGVnfGltYWdlcy9oYjgvaDY2LzkyMzQ0NDQ0NTE4NzAuanBnfGYyNzQ3N2Y0ODdmZWMxNTM1ZGFhMDdkODI0ZDc0ZmMxZjg5MzQwNDBhYzZmNzllODgxZmUzZmQ1ZmRiZDk2YTM', '$2,024.25', 'Un impresionante rascacielos para gatos, diseñado para que tu felino se sienta en la cima del mundo.', 'Accesorios', 'NA', 'NA'),
(112, 'Mueble para Gato Tipo Árbol Múltiples Texturas', 'EveryYay',2, 'https://www.petco.com.mx/medias/300ftw-132572.jpg?context=bWFzdGVyfHJvb3R8MzEyMjd8aW1hZ2UvanBlZ3xoYTkvaGJkLzEwNjA2NDM2NzEyNDc4LzMwMGZ0d18xMzI1NzIuanBnfDZhOGRkZjIxOWQ2YTgwNTIwZTI0NmQ1YWJmNzVlY2M2ZDNjNTAxM2U1ZTg3YWRiNGMzMjNiZGQ0OWNkODMxMjA', '$2,024.25', 'Un árbol para gatos con múltiples texturas que mantendrá a tu felino entretenido y feliz.', 'Accesorios', 'NA', 'NA'),
(113, 'Rascador de Cartón en Forma de Rampa', 'EveryYay',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1MDA1NXxpbWFnZS9qcGVnfGltYWdlcy9oMjEvaDE0Lzk1MzUwODAzNjYxMTAuanBnfDg2N2YxZjZhNGM5MDIzNjJjMDc3MGYyNGE4MWE0NmNlZjVmZmNmNDhkNjZlM2I2M2U2MWZlOGMyYWM4MTc2MWI', '$319.91', '¡Diversión y ejercicio en uno! Este rascador de cartón en forma de rampa es ideal para el juego y la salud de tu gato.', 'Accesorios', 'NA', 'NA'),
(114, 'Repuesto para Rascador Extra Ancho de Cartón para Gato', 'EveryYay',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxNzUzNnxpbWFnZS9qcGVnfGltYWdlcy9oMzEvaGYxLzk1MzUwNDEzMzk0MjIuanBnfDhhYTZjZGNhYWUzMjFlMzg3YTBjNTI3OTg4MzU3ZTFjZDA2ZGJlZmM0YmVhOWRiMTc5YjA4MTE1NWQ0NDY3MGI', '$141.79', 'Mantén siempre fresco el rascador de tu gato con estos prácticos repuestos de cartón extra ancho. ¡Incluye dos piezas!', 'Accesorios', 'NA', 'NA'),
(115, 'Varita Multicolor Diseño Oruga', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/300ftw-112157.jpg?context=bWFzdGVyfHJvb3R8MjEzMjN8aW1hZ2UvanBlZ3xoODQvaDY4LzEwNjA2Mzc4Mjg3MTM0LzMwMGZ0d18xMTIxNTcuanBnfDYxM2UzODJkNzU2ZmQ2MjYwMGEwOGY5MmY3ZTUyOTU2MzdkY2Y5ZjUzMjM4NjllOGVkZTA5N2E4MjNiODUzMjk', '$59.25', '¡Haz que tu gato salte de alegría con esta varita multicolor! El diseño de oruga la hace aún más divertida.', 'Juguetes', 'Multicolor', 'NA')
(116, 'Puntero Láser Diseño Flores', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyMzU4MHxpbWFnZS9qcGVnfGltYWdlcy9oYmYvaDQyLzkxNTk4NTUyNDMyOTQuanBnfGIyMzQ3MDMzNjY5ZTE0NWMzNWVmNTQ2NWUzYTI3MmI2ODQxYTJmOTk2NTY0ZjEyNzY4NDFhY2FkNDdkMDIwMjQ', '$74.25', '¡Tu gato no podrá resistirse a este puntero láser con diseño de flores! Perfecto para sesiones de juego interminables.', 'Juguetes', 'Rosa', 'NA'),
(117, 'Ratoncitos Divertidos con Plumas, 2 Piezas', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/112261.jpg-300ftw?context=bWFzdGVyfHJvb3R8Mzk0OTV8aW1hZ2UvanBlZ3xoNjgvaGJiLzkxOTYxNTAzODI2MjIuanBnfGIzZjNjMjBjZjljYzIyN2Y5Y2FjYzNmZTY2YWM5ZWEwZTUwMjQ2YzAzOWY4OTBkYTIyZTgyM2Q5MzYxYWIxMTA', '$44.25', 'Estos ratoncitos con plumas mantendrán a tu gato ocupado y feliz. ¡Diversión asegurada!', 'Juguetes', 'Surtido', 'NA'),
(118, 'Túnel Colapsable Diseño Galaxia', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/137833.jpg-300ftw?context=bWFzdGVyfHJvb3R8NjQ5MTh8aW1hZ2UvanBlZ3xoNzIvaDFhLzEwMjE5MzE1MDY4OTU4LzEzNzgzMy5qcGdfMzAwZnR3fGJkM2EwZDFjZjhlOGFmYjRjMjg1ZDIxYTZkYTZlYzQ5MTBhZTkxYzA5NTFkNGRmNDU4NmFlMjc5ZmJlMmI1NmQ', '$276.75', 'Un túnel colapsable con diseño de galaxia que mantendrá a tu gato entretenido por horas.', 'Juguetes', 'Azul', 'Pequeño'),
(119, 'Playful by Nature Pelota de Catnip, 1 Pieza', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w3OTAzMXxpbWFnZS9qcGVnfGltYWdlcy9oNWYvaDc4LzkzMjM0MDY2NTU1MTguanBnfDAxNDAxMzc4NGNmNjFhZDAzYjEwNTY5NzMwMjk2ZmMyNzY1YTA4NDAyMjI1MzcwYTMwOTNkODkzOTc2Nzk2MGU', '$74.25', 'Esta pelota de catnip mantendrá a tu gato activo y feliz. ¡Perfecta para momentos de diversión!', 'Juguetes', 'NA', 'NA'),
(120, 'Varita con Plumas de Faisán, 1 Pieza', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyNjIzMHxpbWFnZS9qcGVnfGltYWdlcy9oZjIvaGRjLzkxODM1MzQ2MTI1MTAuanBnfDM4NmIwZmYzZWQzNzY1ODkwMjg5ZDRjOGUwOWYxYzA0YjllZjQ3NzZkOTYwYTA1MDhiMWY2M2FhMjUzMTQzY2U', '$59.25', 'Haz que tu gato se divierta con esta varita de plumas de faisán. ¡Un juguete irresistible!', 'Juguetes', 'Variado', 'NA'),
    