INSERT INTO products (id, title, marca, fk_id_petType, image, price, description, fk_id_category, color, size) VALUES 
(41, 'Mueble Tipo Torre con Rampa', 'EveryYay', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wzNTc1N3xpbWFnZS9qcGVnfGltYWdlcy9oNmIvaGU3Lzk1MzgzNjY3MzQzNjYuanBnfGMxNWVhY2E1ODBmMzUzOGMyMTc5NWVjZDQ1MGUwOTcwOWM0NzVjZTVjNjQ5OTRiODM1MTk1ZjZjNDc4Mjk2MTQ', '$1,079.40', 'Mueble para Gatito Tipo Torre con Rampa.', 4, 'Gris', 'NA'),
(42, 'Mueble Tipo Torre Con Guarida y Repisa', 'EveryYay', 2, 'https://www.petco.com.mx/medias/300ftw-142229.jpg?context=bWFzdGVyfHJvb3R8MzQ4Mjd8aW1hZ2UvanBlZ3xoMjEvaGZhLzEwNjA2NjE1NzU2ODMwLzMwMGZ0d18xNDIyMjkuanBnfGUxZmI4YzBkOTEzYmFhZTc3OWJjNTlmNDVmYTU1MmQ3OTA3YmY5N2VkZjIzYWU1MjM3ZjJlMWI4MzRkZDQ0NGQ', '$1,679.40', 'Mueble Tipo Torre con Guarida y Repisa para Gato, Beige.', 4, 'Beige', 'NA'),
(43, 'Alberca de Pelotas para Juegos', 'Marshall', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyNDE5MXxpbWFnZS9qcGVnfGltYWdlcy9oYTQvaDI2Lzk1MjkxNTczNTM1MDIuanBnfDFlNmYwOGZhMzU5YjJhNTU5NWM1ZGY5ZWIxMDJkNTJkY2FmYzMyZWQ2NTQyYjA0NGM3OGI2YTZlMGU5YWUzMjM', '$775.00', 'Marshall Alberca de Pelotas para Juegos Pop-n-Play.', 4, 'NA', 'NA'),
(44, 'Chew Esferas de Sauce', 'You & Me', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w2MTA4OXxpbWFnZS9qcGVnfGltYWdlcy9oZTQvaDIzLzkyMDEzNTU4MTY5OTAuanBnfGQyMjBmNWQ5MGY3ZmI5NjI4OTI1ZDJlMWQxNmI5MzEyZGYzMWYxOWI2MjcyYzhiZWNiYzcyNTFhNDQ1ZmMyODk', '$123.50', 'You & Me Chew Esferas de Sauce, 3 Piezas.', 4, 'NA', 'NA'),
(45, 'Bolas Rodadoras para Pequeñas Mascotas', 'Oxbow', 3, 'https://www.petco.com.mx/medias/133191.jpg-300ftw?context=bWFzdGVyfHJvb3R8NjI5MTV8aW1hZ2UvanBlZ3xoYjcvaDVmLzk1NzU1MzcwNDk2MzAuanBnfDcxYTU3NmQ0Y2U4MzA2NjFiZGJmMGFlYTg5ODY0OTliZDJlNzFjOGU5YzJmMzRkYTVjZThlNTkxODYwZTMyNTA', '$161.50', 'Oxbow Enriched Life Bolas Rodadoras para Pequeñas Mascotas.', 4, 'NA', 'NA'),
(46, 'Escondite Castillo', 'You & Me', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w0ODA3OXxpbWFnZS9qcGVnfGltYWdlcy9oZTIvaDQxLzkyMDEzMTk1NDI4MTQuanBnfDFlYzY0ODljZjVlMzU4ZWJhMjNiNWYxYmQxMDk5OTlmYzc3YjdjZDJkOWM0NDA1YjExODZhMGExZDIzN2ZlOTQ', '$145.00', 'You & Me Escondite Castillo, Mediano.', 4, 'NA', 'NA'),
(47, 'Túnel', 'Ware', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1MjI5MHxpbWFnZS9naWZ8aW1hZ2VzL2gwMy9oNGQvODg0ODEwMzU3MTQ4Ni5naWZ8MjYyMjhiMjJkY2U4ODY3ZTA0NjI1ZGY0YzU4N2MzMGQ2ZWE5YjVjMGZkNWQ3YzY4NzMzNzMyNzc0ODE2NzI1Nw', '$289.75', 'Ware Túnel, XX-Grande.', 4, 'NA', 'NA'),
(48, 'Microchip Para Mascotas Perros y Gatos', 'Chip Mascotas', 1, 'https://m.media-amazon.com/images/I/61RcC5iGZML._AC_SL1200_.jpg', '$850.75', '1x Microchip de 7mm con aplicador, 1 Pasaporte para mascotas, 1 Placa inteligente NFC & QR, 1 Certificado QR/Nfc, 4 Tarjetas de Identificación de microchip, 6 Etiquetas con el número del microchip, 1 Registro de microchip en plataforma de por vida.', 5, 'NA', 'NA'),
(49, 'Bebedero Mason', 'Stokes Wildbird', 4, 'https://www.petco.com.mx/medias/125017.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDE4NjJ8aW1hZ2UvanBlZ3xoMmEvaGM1LzEwNTI3ODg5MTk1MDM4LzEyNTAxNy5qcGdfMzAwZnR3fDIwNzdlNjIwNjI2MGY1NmJkMTBlMGJkYTViMmJiY2E4Njg0MzJjNDIwNjdmNmNhMDVlOGJjNzJmZTcwMGFmZTQ', '$669.00', 'Un bebedero encantador con un diseño clásico de Mason Jar, perfecto para atraer colibríes.', 1, 'NA', 'NA'),
(50, 'Bebedero Amatista', 'Stokes Wildbird', 4, 'https://www.petco.com.mx/medias/125016.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzY3ODV8aW1hZ2UvanBlZ3xoNTgvaDA5LzEwNTI3ODg3ODg0MzE4LzEyNTAxNi5qcGdfMzAwZnR3fGRiYWJmNjZmNDcwMjk1YjJiNzIwN2M4MjE4MDJkOTg0MjI1ZWVmYzNkMmY1OGVlYjdjZDNmZjhjY2FhYWIwYTE', '$679.00', 'Bebedero de color amatista, atractivo y diseñado específicamente para colibríes.', 1, 'Amatista', 'NA');





























(81, 'Bird Banquet Original Formula Hueso de Jibia para Aves', 'Zoo Med',4,'https://www.petco.com.mx/medias/300ftw-130687.jpg?context=bWFzdGVyfHJvb3R8ODkyNzl8aW1hZ2UvanBlZ3xoNDMvaGJmLzEwODA0MzY3ODE4NzgyLzMwMGZ0d18xMzA2ODcuanBnfDUyMTM5YjZkMjQ0MTRiZmQ3ODkzNWE4MWE5NDk2OTRlZmMxNjFiN2U5YmZkOTU1NjEwYzFmNTkwYjgyNjExZGM', '$46.55',' Este producto de 28.34g es ideal para aves, proporcionando calcio y minerales esenciales para su salud.',' Medicamentos',' NA', '28.34g'),
(82, 'Bird Banquet Fruit Formula Hueso de Jibia con Fruta para Aves', 'Zoo Med', 4, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMTA2MjR8aW1hZ2UvanBlZ3xpbWFnZXMvaGQzL2g2MC85NDAwMDk3MzQxNDcwLmpwZ3xkM2Q4YjUxMDFhNDJhMGZhMDQwYWU1NWMzOGYwZWU3MjA0NmEzNGEyYTQyM2E2MTdiMDI3ZDFkNjE2MWE4Yjk1', '$46.55', 'Este complemento está diseñado para promover la salud de las aves con una mezcla sabrosa de jibia y frutas, aportando nutrientes esenciales.', 'Medicamentos', 'NA', '28.34g'),
(83, 'Bird Banquet Mealworm Formula Hueso de Jibia con Gusano de Harina para Aves', 'Zoo Med', 4, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMTMyNTl8aW1hZ2UvanBlZ3xpbWFnZXMvaDllL2hhMS85NDAwMDk3NzAxOTE4LmpwZ3xkMzRkOWJmZDBhY2RhZjYxOGNiODk0MmEyNmYxNDg1OWNiMDhmZTRkZDE1NDc5NDkzODdjNzViYzEwYjU0NjA4', '$46.55', 'Ideal para aves que disfrutan de una dieta rica en proteínas, este producto combina jibia con gusanos de harina para una nutrición completa.', 'Medicamentos', 'NA', '28.34g'),
(84, 'Bird Banquet Vegetable Formula Hueso de Jibia con Vegetales para Aves', 'Zoo Med', 4, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMTIyODJ8aW1hZ2UvanBlZ3xpbWFnZXMvaGZiL2hhYy85NDAwMDk4NDg4MzUwLmpwZ3w3NzQxN2RmZmFmNjM1YTU4OGQ5ZjBkMTRjMzA5Njg2ZjkwZDIwNWVmODMwZmFkMTFkYTNiMDE3MjJiZjc0NWQ3', '$46.55', 'Esta fórmula mezcla jibia con una variedad de vegetales, ofreciendo una opción saludable y deliciosa para tus aves.', 'Medicamentos', 'NA', '28.34g'),
(85, 'Bloque Mineral para Ave', 'Zoo Med', 'Aves', 'https://www.petco.com.mx/medias/300ftw-142128.jpg?context=bWFzdGVyfHJvb3R8MjM2NjN8aW1hZ2UvanBlZ3xoNDgvaDhiLzEwNjA3MTMyMjQ2MDQ2LzMwMGZ0d18xNDIxMjguanBnfDIxNTQ2ODhhYjFmMmY4MjkwYWM0ZTRlNDU4OWRmMDhhMTBlMDNiNjlhNGY4YjdkYjJmNWI1OWYwMjczZDgwZWM', '$169.00', 'Bloque mineral grande para aves, que aporta calcio y minerales esenciales para una dieta equilibrada. Ideal para aves de tamaño grande.', 'Medicamentos', 'NA', 'Grande'),
(86, 'Mezcla de Heno Pasto Timothy y Pasto de Orchard para Roedores', 'Oxbow', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMDc0Nzh8aW1hZ2UvanBlZ3xpbWFnZXMvaDk5L2g2Zi85NDEyNDU5NTYwOTkwLmpwZ3w3YWQ0MWE5NDg2YzBjOWY0MDI1MTI4ZjlkZjBiZjM0MmQ4MmYwMzU1MjJiZDEyMDg0ZTNkMzFkYmExM2Q2YjFh', '$332.50', 'Ideal para roedores de todas las edades, proporcionando una mezcla nutritiva y rica en fibra.', 'Alimento', 'NA', '1.1kg'),
(87, 'Premium Alimento para Conejo Adulto', 'Cunipic', 3, 'https://www.petco.com.mx/medias/300ftw-114755.jpg?context=bWFzdGVyfHJvb3R8NjcwOTF8aW1hZ2UvanBlZ3xoYTIvaGY1LzEwNjQ2MTIxNzA5NTk4LzMwMGZ0d18xMTQ3NTUuanBnfGNmN2EyMjY5YzY1ZGY5NmZkNDNkMTAzNWU5ZGZmODFhOWVlOTIxMjFmZGEyMjFmMTZiZDZhNmY4OTU0Y2E2NjM', '$463.25', 'Formula especial para satisfacer las necesidades nutricionales de los conejos adultos, promoviendo su salud general.', 'Alimento', 'NA', '5kg'),
(88, 'Western Pasto Timothy para Roedores Todas las Edades', 'Oxbow', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMDk5MjV8aW1hZ2UvanBlZ3xpbWFnZXMvaGQ3L2hjYS85NDAwMDk4NDg4MzUwLmpwZ3w5Yzg1MmMxMTc3ZjIyMWVhNzg4ZjBjMmJlNjY4OTQ5ZDczZjQ2YzgxYTkwNmIwZWE2MWRiNTM5ZDAzMTdlYWFi', '$332.50', 'Este heno es una fuente rica en fibra que favorece una digestión saludable.', 'Alimento', 'NA', '1.1kg'),
(89, 'Alpha Pro Alimento Completo para Conejo Adulto', 'Cunipic', 3, 'https://www.petco.com.mx/medias/300ftw-126546.jpg?context=bWFzdGVyfHJvb3R8NzE2MzF8aW1hZ2UvanBlZ3xoMzYvaDAzLzEwNzMzNjU1MTMwMTQyLzMwMGZ0d18xMjY1NDYuanBnfGI2NzkwOThhNTM0MjlmODM5NmViY2I3MDNjNDI3NDlhNDg5OTg1YWM2Mzg2MTMwZjZlM2I1ZDEzMjMwNjkwNGQ', '$437.75', 'Alimento completo y equilibrado para conejos adultos. Rico en fibra, favorece la digestión y la salud dental.', 'Alimento', 'NA', '1.7kg'),
(90, 'Essentials Alimento Seco para Conejo Adulto', 'Oxbow',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMDA2MjN8aW1hZ2UvanBlZ3xpbWFnZXMvaGJlL2g0NC85NDAwMTA1NTk5MDA2LmpwZ3w5OWZiNTJkM2JhODllYWIyNTA3MzNmNzRjNjM4MDAwM2I4NDIxMGU1ZjQzNmY0ZjY3ZDA0NGRiNjUxODI2YWNh', '$361.00', 'Alimento seco de alta calidad para conejos adultos. Promueve la salud digestiva y dental con ingredientes naturales.', 'Alimento', 'NA', '2.25kg'),
(91, 'Alimento Seco para Conejo Enano Adulto', 'Versele-Laga',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1NTY4N3xpbWFnZS9qcGVnfGltYWdlcy9oMmUvaDc3Lzk0NTc0NDk0MzUxNjYuanBnfGExYzg0NDA4NjRkMGMzNTJmOTZkMzJlY2U0Nzk5MjhiOGZkNzMzZWRlZTI0NDI0NDNmODQ2OTEzNmI2ZGM4MTQ', '$503.50', 'Alimento completo para conejos enanos adultos. Favorece la digestión y la salud del pelaje con ingredientes naturales.', 'Alimento', 'NA', '1.7kg'),
(92, 'Premium Alimento para Conejo Junior', 'Cunipic',3, 'https://www.petco.com.mx/medias/300ftw-114701.jpg?context=bWFzdGVyfHJvb3R8NjQ5MTB8aW1hZ2UvanBlZ3xoMmMvaGUwLzEwNjQ2MTE4NzYwNDc4LzMwMGZ0d18xMTQ3MDEuanBnfDU5YjlmYTYxZmYyMDRjNTEzZTMyODEyZTJiODcyNDhmZmNmOGRiMDQ4OWQ5MTgzMWU1ODM3ZWY5ODg1NjYwMDM', '$284.75', 'Alimento premium para conejos jóvenes. Nutrición balanceada con vitaminas esenciales para un crecimiento saludable.', 'Alimento', 'NA', '2.5kg'),
(93, 'Western Pasto Timothy para Roedores Todas las Edades', 'Oxbow',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w5NjU1MnxpbWFnZS9qcGVnfGltYWdlcy9oYTkvaDg5Lzk0MTI0NTM5NTc2NjIuanBnfGFiOWRmYWIwOTIzM2FkZDIwMDNhMjViZGM3MWE5MzU2MDExZGQ0MDBiMDI0MjA0ZWU2MTQ5ZDAzMTU2NzE2MjI', '$175.75', 'Pasto Timothy natural para roedores de todas las edades. Rico en fibra, favorece la digestión y el desgaste dental.', 'Alimento', 'NA', '425g'),
(94, 'Alimento Alpha Pro Light para Conejo Adulto', 'Cunipic',3, 'https://www.petco.com.mx/medias/135134.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDExMzJ8aW1hZ2UvanBlZ3xoYjUvaGNjLzk5NjE4NTIyMDcxMzQvMTM1MTM0LmpwZ18zMDBmdHd8N2E3NmMxZjIwMzVjZGIwNTBlNzA1ZTNjNzlkOGM0MWRiYjNiZDcyODM0NTBhMzY4OGYyMDczYjc1ODNmZGIwNw', '$433.50', 'Alimento light para conejos adultos. Bajo en calorías y alto en fibra para un peso saludable.', 'Alimento', 'NA', '1.7kg'),
(95, 'Alimento Garden Select para Conejo Adulto', 'Oxbow',3, 'https://www.petco.com.mx/medias/136394.jpg-300ftw?context=bWFzdGVyfHJvb3R8MjMyNDZ8aW1hZ2UvanBlZ3xoYTQvaGQyLzEwMzc0MzIxNTA0Mjg2LzEzNjM5NC5qcGdfMzAwZnR3fDZmZDI4OGRkODNjZTQ3ZDU1MjIzYzcxZDcxYjcyZWQ1YzIwNGE1YTUzYTAwYjUwNzkwYTQ1YmIwNmRiYjFlZmY', '$418.00', 'Alimento natural para conejos adultos. Con ingredientes seleccionados que promueven una salud óptima.', 'Alimento', 'NA', '1.8kg');
(96, 'Kit de Grooming', 'Ware',3, 'https://www.petco.com.mx/medias/300ftw-102448.jpg?context=bWFzdGVyfHJvb3R8Nzg0NDV8aW1hZ2UvanBlZ3xoNjMvaDNmLzEwNjQxNzU4NTg0ODYyLzMwMGZ0d18xMDI0NDguanBnfGU4NjUxZGIzNTMwNTg5OGY4OThlOTYyNWFhNGVhMGM2ZWY2MDQ5MDZlYWI4YWIzODUzZDI5YWJjMTAyNzViZTU', '$251.75', 'Mantén a tu conejo siempre impecable con este completo kit de grooming.', 'Accesorios', 'NA', 'NA'),
(97, 'Limpiador Hábitat para Mamíferos', 'Sophresh',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wzNDU3NHxpbWFnZS9qcGVnfGltYWdlcy9oMmQvaDI5LzkyNTg2MjkwNzA4NzguanBnfDEzNTA3NWJhYjI5OGY0NzZjMzQ0N2IwMDE0NmM2YmY5ZTBhOTYxMjU0NWQ2Y2RhZTZkODA1ODZiY2U2MDZmMjk', '$144.00', 'Limpia y refresca el hábitat de tu conejo con este limpiador de hábitats.', 'Medicamentos', 'NA', '473 ml'),
(98, 'Animal Mineral Block Hueso de Jibia para Roedores', 'Zoo Med',3, 'https://www.petco.com.mx/medias/300ftw-130683.jpg?context=bWFzdGVyfHJvb3R8OTc0ODl8aW1hZ2UvanBlZ3xoZTgvaGE3LzEwODA0MzY3MTYzNDIyLzMwMGZ0d18xMzA2ODMuanBnfGViODg3OWExOWZmMTAxNzVkYmQwZjM3ZjU1ZDU0YWFiNjFjNGQzOWRlZjBjNzI1MzJhOWMzMGJmNjBkMGJlYmY', '$46.55', 'Dale a tu roedor un suplemento esencial con este bloque mineral de jibia.', 'Medicamentos', 'NA', '24 g'),
(99, 'Escondite Tejido', 'Oxbow',3, 'https://www.petco.com.mx/medias/133204.jpg-300ftw?context=bWFzdGVyfHJvb3R8NTc1NjV8aW1hZ2UvanBlZ3xoNWUvaDE3Lzk1NzU1NTIyNTM5ODIuanBnfGY1ZmQ2MzEzZmM4MzZiMzdiMDNkNjlkOTZmYWE2M2RjN2Y3NzljOWU0YjU3NzJmMDI1ZGU4MjM5OWIwZmVkMWI', '$555.00', 'Un escondite perfecto para tu conejo, donde puede sentirse seguro y relajado', 'Accesorios', 'NA', 'Mediano'),
(100, 'Plato Cerámica para Pequeños Mamíferos', 'Yolcame',3, 'https://www.petco.com.mx/medias/138842.jpg-300ftw?context=bWFzdGVyfHJvb3R8MTE4NzV8aW1hZ2UvanBlZ3xoMTYvaDRjLzEwMzEwNDY1NzgxNzkwLzEzODg0Mi5qcGdfMzAwZnR3fDhmNDNmYWVmOWY2NGYyMGIwZjA3OTUzOGU2YTM4Y2UwNDNhNGQwNDgyMWU2NWFhY2ZlOTdjZDdmYzc1NjNmNmI', '$120.00', 'Un plato elegante y resistente para las comidas de tu pequeño amigo peludo.', 'Accesorios', 'NA', 'Grande'),
(101, 'Bowl para Alimentación Lenta', 'Oxbow',3, 'https://www.petco.com.mx/medias/133202.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzkyNTB8aW1hZ2UvanBlZ3xoNjMvaDY3Lzk1NzU1NDk1MDE0NzAuanBnfDFhMTYxN2Y3YjBkN2UyNDdkNDY0OWZlM2RiOWVmZGZmN2JjNDQzMTE4MDNhMDNiMjIyZTU5ODMzZDMzMWY5N2E', '$280.00', 'Un comedero diseñado para que tu conejo coma más despacio y disfrute cada bocado.', 'Accesorios', 'NA', 'Chico'),
(102, 'Pala para Pequeñas Mascotas', 'Sophresh',3, 'https://www.petco.com.mx/medias/138943.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzU3NTh8aW1hZ2UvanBlZ3xoZTMvaDdiLzEwMDc0MDU4NDU3MTE4LzEzODk0My5qcGdfMzAwZnR3fDBlNjNmY2UzNmVjYjEwYmMzYmJlY2U0ZmJkOGNlOTA3NGVmYTk0MjAzMWFkOTJiZTI5NjMxYjM2NzIwNGRiZDc', '$50.00', 'La herramienta ideal para mantener la jaula de tu mascota limpia y ordenada.', 'Accesorios', 'NA', 'NA'),
(103, 'Bebedero a Prueba de Mordidas', 'Kaytee',3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxNzAyOHxpbWFnZS9naWZ8aW1hZ2VzL2hkNy9oYTQvODg0ODE1NDI5NjM1MC5naWZ8M2IxMzc5NzBhYTY3MTUyMjlmYTIzNWI2Njk5Mzc3NmJlOWY2NjliYmE1YmY5Mjg1ZWYxOWE5MmFjZjg4MjVkYw', '$259.00', 'Un bebedero duradero y resistente, perfecto para evitar mordidas y fugas.', 'Accesorios', 'NA', '355 ml'),
(104, 'Dispensador de Heno', 'Kaytee',3, 'https://www.petco.com.mx/medias/300ftw-102112.jpg?context=bWFzdGVyfHJvb3R8NzA3OTJ8aW1hZ2UvanBlZ3xoODQvaGJkLzEwODMzMTE5NTEwNTU4LzMwMGZ0d18xMDIxMTIuanBnfGZiNTk5NDgwNzVlNWZmMmM0MjJhOGRmOGUxODBhMjE5ODQ2MzEyMGM0OWIxMzdkODkzNmVkOGE3NmZjY2M5Yjg', '$329.00', 'Mantén el heno fresco y accesible para tu conejo con este práctico dispensador.', 'Accesorios', 'NA', 'NA'),
(105, 'Mueble para Gato Tipo Árbol de 7 Niveles', 'You & Me',2, 'https://www.petco.com.mx/medias/300ftw-110717.jpg?context=bWFzdGVyfHJvb3R8MzQzNjl8aW1hZ2UvanBlZ3xoM2YvaDU0LzEwNjExMDU3MDAwNDc4LzMwMGZ0d18xMTA3MTcuanBnfGY0YWNkYjZjYzg4ODBkM2M2MTc2YWVlOWM3MmMwODExMTJmYzZiZDkxYWE4MmU4OTZkZjUxODgyYWM5NTZhZjU', '$2,699.25', 'Un árbol para gatos con múltiples texturas que mantendrá a tu felino entretenido y feliz.', 'Accesorios', 'NA', 'NA')
(106, 'Mueble Tipo Árbol Deluxe Ultra Resistente', 'You & Me',2, 'https://www.petco.com.mx/medias/300ftw-128164.jpg?context=bWFzdGVyfHJvb3R8MjgyNjR8aW1hZ2UvanBlZ3xoMTAvaDgyLzEwNjA2NDI1NTcxMzU4LzMwMGZ0d18xMjgxNjQuanBnfDc4NTZkZGY1MDE0MjhmZTFhYmQ1ZWJiNmI0YzhmODE1NWY1OTEyMmYzOTYyNzk4MGM2YzhiNjQ5OWFmMzEyNTM', '$3,299.25', 'Un árbol para gatos de lujo, con 7 niveles que harán que tu felino se sienta en el paraíso. ¡Ideal para trepar y explorar!', 'Accesorios', 'NA', 'NA'),
(107, 'Mueble para Gatos Senior y de Talla Grande', 'EveryYay',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wzNDEzNHxpbWFnZS9qcGVnfGltYWdlcy9oYTIvaDJhLzk1MzUxMDQ1ODE2NjIuanBnfDY1ZmJjMmQxMWE0NDc1MTZlOWMzYjQyODZkYzA2YmU0Yjc5NmM4ZjBiMDUzNzA2Mjk4MjE5NGI4ZTQxM2EwNDQ', '$2,474.25', 'Perfecto para gatos mayores y grandes, este árbol con rampa y escondite proporciona comodidad y diversión.', 'Accesorios', 'NA', 'NA'),
(108, 'Cama Tipo Cueva con Orejitas y Cola', 'Harmony',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1OTAzNXxpbWFnZS9qcGVnfGltYWdlcy9oYjMvaDg3Lzk1NDI5NTk3MjY2MjIuanBnfDk2OGZjNjQxYmU4YzI1MWQwOTVjMGQwZWNkMDJiMWI2MTgzMjBlNzhjZGYzMDBiODBhYTNiNzIzZjJlNWE3ZmE', '$399.20', 'Una cueva acogedora con orejitas y cola que mantendrá a tu gato calentito y seguro. ¡Demasiado adorable para resistir!', 'Accesorios', 'Gris', 'NA'),
(109, 'Rascador de Cartón en Forma de Sofá', 'EveryYay',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1MDM1MXxpbWFnZS9qcGVnfGltYWdlcy9oMjYvaDZlLzk1MzUwODM4Mzk1MTguanBnfGUxYWZjODUwNDY3ODYwYjVlMmU5NDkzOTIxYmNjNjYzYzZlZGY1MDRkNjNlZGFmMjcwOTliYTZkMWIzZTFjMmQ', '$336.75', 'Un rascador elegante en forma de sofá que incluye catnip para atraer a tu gato. ¡Diversión y estilo en uno!', 'Accesorios', 'NA', 'NA'),
(110, 'Cama Tipo Cueva', 'Harmony',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1NzE4MnxpbWFnZS9qcGVnfGltYWdlcy9oNmUvaDc4Lzk1NDI5NTkzNjYxNzQuanBnfDcwMWY4ZTlkNjQwZTUyNDUxODRhMzI4YzE0M2YyODg2NDBmYmI5NGNhZTAyNTg2YjhkMWNjZmM5OThjYTI3NDQ', '$399.20', 'Una cama tipo cueva en color gris, perfecta para que tu gato se acurruque y descanse cómodamente.', 'Accesorios', 'Gris', 'NA'),
(111, 'Mueble para Gato Tipo Árbol Rascacielo', 'You & Me',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w3MTU1MXxpbWFnZS9qcGVnfGltYWdlcy9oYjgvaDY2LzkyMzQ0NDQ0NTE4NzAuanBnfGYyNzQ3N2Y0ODdmZWMxNTM1ZGFhMDdkODI0ZDc0ZmMxZjg5MzQwNDBhYzZmNzllODgxZmUzZmQ1ZmRiZDk2YTM', '$2,024.25', 'Un impresionante rascacielos para gatos, diseñado para que tu felino se sienta en la cima del mundo.', 'Accesorios', 'NA', 'NA'),
(112, 'Mueble para Gato Tipo Árbol Múltiples Texturas', 'EveryYay',2, 'https://www.petco.com.mx/medias/300ftw-132572.jpg?context=bWFzdGVyfHJvb3R8MzEyMjd8aW1hZ2UvanBlZ3xoYTkvaGJkLzEwNjA2NDM2NzEyNDc4LzMwMGZ0d18xMzI1NzIuanBnfDZhOGRkZjIxOWQ2YTgwNTIwZTI0NmQ1YWJmNzVlY2M2ZDNjNTAxM2U1ZTg3YWRiNGMzMjNiZGQ0OWNkODMxMjA', '$2,024.25', 'Un árbol para gatos con múltiples texturas que mantendrá a tu felino entretenido y feliz.', 'Accesorios', 'NA', 'NA'),
(113, 'Rascador de Cartón en Forma de Rampa', 'EveryYay',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1MDA1NXxpbWFnZS9qcGVnfGltYWdlcy9oMjEvaDE0Lzk1MzUwODAzNjYxMTAuanBnfDg2N2YxZjZhNGM5MDIzNjJjMDc3MGYyNGE4MWE0NmNlZjVmZmNmNDhkNjZlM2I2M2U2MWZlOGMyYWM4MTc2MWI', '$319.91', '¡Diversión y ejercicio en uno! Este rascador de cartón en forma de rampa es ideal para el juego y la salud de tu gato.', 'Accesorios', 'NA', 'NA'),
(114, 'Repuesto para Rascador Extra Ancho de Cartón para Gato', 'EveryYay',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxNzUzNnxpbWFnZS9qcGVnfGltYWdlcy9oMzEvaGYxLzk1MzUwNDEzMzk0MjIuanBnfDhhYTZjZGNhYWUzMjFlMzg3YTBjNTI3OTg4MzU3ZTFjZDA2ZGJlZmM0YmVhOWRiMTc5YjA4MTE1NWQ0NDY3MGI', '$141.79', 'Mantén siempre fresco el rascador de tu gato con estos prácticos repuestos de cartón extra ancho. ¡Incluye dos piezas!', 'Accesorios', 'NA', 'NA'),
(115, 'Varita Multicolor Diseño Oruga', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/300ftw-112157.jpg?context=bWFzdGVyfHJvb3R8MjEzMjN8aW1hZ2UvanBlZ3xoODQvaDY4LzEwNjA2Mzc4Mjg3MTM0LzMwMGZ0d18xMTIxNTcuanBnfDYxM2UzODJkNzU2ZmQ2MjYwMGEwOGY5MmY3ZTUyOTU2MzdkY2Y5ZjUzMjM4NjllOGVkZTA5N2E4MjNiODUzMjk', '$59.25', '¡Haz que tu gato salte de alegría con esta varita multicolor! El diseño de oruga la hace aún más divertida.', 'Juguetes', 'Multicolor', 'NA')
(116, 'Puntero Láser Diseño Flores', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyMzU4MHxpbWFnZS9qcGVnfGltYWdlcy9oYmYvaDQyLzkxNTk4NTUyNDMyOTQuanBnfGIyMzQ3MDMzNjY5ZTE0NWMzNWVmNTQ2NWUzYTI3MmI2ODQxYTJmOTk2NTY0ZjEyNzY4NDFhY2FkNDdkMDIwMjQ', '$74.25', '¡Tu gato no podrá resistirse a este puntero láser con diseño de flores! Perfecto para sesiones de juego interminables.', 'Juguetes', 'Rosa', 'NA'),
(117, 'Ratoncitos Divertidos con Plumas, 2 Piezas', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/112261.jpg-300ftw?context=bWFzdGVyfHJvb3R8Mzk0OTV8aW1hZ2UvanBlZ3xoNjgvaGJiLzkxOTYxNTAzODI2MjIuanBnfGIzZjNjMjBjZjljYzIyN2Y5Y2FjYzNmZTY2YWM5ZWEwZTUwMjQ2YzAzOWY4OTBkYTIyZTgyM2Q5MzYxYWIxMTA', '$44.25', 'Estos ratoncitos con plumas mantendrán a tu gato ocupado y feliz. ¡Diversión asegurada!', 'Juguetes', 'Surtido', 'NA'),
(118, 'Túnel Colapsable Diseño Galaxia', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/137833.jpg-300ftw?context=bWFzdGVyfHJvb3R8NjQ5MTh8aW1hZ2UvanBlZ3xoNzIvaDFhLzEwMjE5MzE1MDY4OTU4LzEzNzgzMy5qcGdfMzAwZnR3fGJkM2EwZDFjZjhlOGFmYjRjMjg1ZDIxYTZkYTZlYzQ5MTBhZTkxYzA5NTFkNGRmNDU4NmFlMjc5ZmJlMmI1NmQ', '$276.75', 'Un túnel colapsable con diseño de galaxia que mantendrá a tu gato entretenido por horas.', 'Juguetes', 'Azul', 'Pequeño'),
(119, 'Playful by Nature Pelota de Catnip, 1 Pieza', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w3OTAzMXxpbWFnZS9qcGVnfGltYWdlcy9oNWYvaDc4LzkzMjM0MDY2NTU1MTguanBnfDAxNDAxMzc4NGNmNjFhZDAzYjEwNTY5NzMwMjk2ZmMyNzY1YTA4NDAyMjI1MzcwYTMwOTNkODkzOTc2Nzk2MGU', '$74.25', 'Esta pelota de catnip mantendrá a tu gato activo y feliz. ¡Perfecta para momentos de diversión!', 'Juguetes', 'NA', 'NA'),
(120, 'Varita con Plumas de Faisán, 1 Pieza', 'Leaps & Bounds',2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyNjIzMHxpbWFnZS9qcGVnfGltYWdlcy9oZjIvaGRjLzkxODM1MzQ2MTI1MTAuanBnfDM4NmIwZmYzZWQzNzY1ODkwMjg5ZDRjOGUwOWYxYzA0YjllZjQ3NzZkOTYwYTA1MDhiMWY2M2FhMjUzMTQzY2U', '$59.25', 'Haz que tu gato se divierta con esta varita de plumas de faisán. ¡Un juguete irresistible!', 'Juguetes', 'Variado', 'NA'),
    
(121, 'Set de 3 Ratoncitos Diseño Safari', 'Leaps & Bounds', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wxMjU4MnxpbWFnZS9qcGVnfGltYWdlcy9oMWEvaGIxLzk0OTczOTc3NTU5MzQuanBnfGVjMTcxZWNkMDAzYTVjYjE4YmNlZWIwZWZiNTQwZGM1OWU0NjljYTgwYmRhODZmYTQ2Y2EwMTFjNjg4MDdiM2U', '$66.75', 'Tres ratoncitos con diseño safari que harán que tu gato se sienta en la selva. ¡Diversión garantizada!', 4, 'Safari', 'NA'),
(122, 'Juguete con Forma de Túnel para Gato', 'Leaps & Bounds', 2, 'https://www.petco.com.mx/medias/133925.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzMwMTJ8aW1hZ2UvanBlZ3xoNmYvaGJkLzk4ODM1NzU3NDY1OTAvMTMzOTI1LmpwZ18zMDBmdHd8Zjg5OWIxOGZmN2I2YWE4Y2NjMDk4MzNjOTNjZmEzOTYyMzMyOGY2YzVhYjExYWMyOTczOWY1NmU2NDFhZWRjZQ', '$374.25', 'Túnel de juego azul diseñado especialmente para mantener a tu gato activo y entretenido. Perfecto para horas de diversión.', 4, 'Azul', 'NA'),
(123, 'Serpiente Electrónica Juguete para Gato, 1 Pieza', 'Leaps & Bounds', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wzMzMwMHxpbWFnZS9qcGVnfGltYWdlcy9oZTYvaGY3Lzk0OTc0MDI4MzQ5NzQuanBnfGM3YTdkYjM4MjZjZjc0OGVjNDZjNWYxYmFjOWQ5YjhkMmNkNjM3YzgyNmYwMDgzMTQ5MjMxYmMwMTY0NWJhMWM
','$186.75', 'Serpiente electrónica que se mueve y hace sonidos, estimulando el instinto cazador de tu gato. Ideal para mantenerlo activo.', 4, 'Verde', 'NA'),
(124, 'Ratita Gris para Gato, 1 Pieza', 'Leaps & Bounds', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyMjM5N3xpbWFnZS9qcGVnfGltYWdlcy9oNTQvaDZmLzkxODM1NDEyOTcxODIuanBnfDBmMDdmNjliNjNhMDY5MWVhOGUyNTUyNmM5YjkyOGFjOWM3MTVjMDY4OWM4ZjZjZTk0MWRhZDM2NjllMDdiMjc', '$51.75', 'Ratita de peluche gris para gatos. Perfecta para el juego diario, estimulando el instinto natural de caza.', 4, 'Gris', 'NA'),
(125, 'Tapete Multitexturas para Jugar y Rascar para Gato', 'Petlinks', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w0NDYyNHxpbWFnZS9qcGVnfGltYWdlcy9oMDYvaGFhLzk1MDU3ODA5MjQ0NDYuanBnfDk5ZTdjYzUzMGYyZTcyYjk1ZDRhM2QxYjNhMGEyMjAyN2I1ZTdjYTU4NDM3OWJkZGZmMGE3ZmU3NTcxZDVlYzE', '$471.75', 'Tapete multitexturas que combina diversión y descanso. Perfecto para rascar, jugar y relajarse.', 4, 'Multicolor', '71 cm'),
(126, 'Collar Antipulgas y Garrapatas para Perro y Gato', 'Seresto', 1, 'https://www.petco.com.mx/medias/300ftw-116475.jpg?context=bWFzdGVyfHJvb3R8Njg4MjV8aW1hZ2UvanBlZ3xoZTAvaGQxLzEwNzQ4NjE4OTY1MDIyLzMwMGZ0d18xMTY0NzUuanBnfDA2MmY1Yzc2MjAyNDE0MWQ2M2U5MjViZmY1YzRkODFmZWM0MTNjODg5ZWQ5Mjk2MmZkYzlmYWVhNWNlYTFjNGQ', '$975.41', 'Collar antipulgas y garrapatas de tamaño chico para perros y gatos. Ofrece protección duradera y efectiva.', 5, 'NA', 'Chico'),
(127, 'Pipeta Antiparasitaria Interna y Externa para Gato', 'Advantage Multi', 2, 'https://www.petco.com.mx/medias/104718.jpg-300ftw?context=bWFzdGVyfHJvb3R8NzU0MDN8aW1hZ2UvanBlZ3xoMGYvaDE1LzEwNTYzNTU5NDU2Nzk4LzEwNDcxOC5qcGdfMzAwZnR3fGU3MmFhZTAxMThlYmE4MjE4NDRmZWZjYzA3NzZlOWIyYmNhOTI1MDJkNjlkNDRkZDQ0OGM5NTFmZjM3Njk0MTk', '$391.16', 'Pipeta antiparasitaria interna y externa para gatos de 4 a 8 kg. Proporciona una protección integral.', 5, 'NA', '4kg a 8kg'),
(128, 'Spray con Efecto Calmante para Gato', 'Feliway', 2, 'https://www.petco.com.mx/medias/122246.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDQzMDB8aW1hZ2UvanBlZ3xoYWIvaGJjLzEwNDk5MTMxNjcwNTU4LzEyMjI0Ni5qcGdfMzAwZnR3fDA3YTk2N2QzYzA3OWEyZTIwOGIyMTcxNTEwZGYxOTE3MjJhMTgwZDVhNmI5YmViZjM4OWEwMjU2YTFkYjA5MmY', '$1,033.70', 'Spray con efecto calmante para gatos. Ayuda a reducir el estrés y la ansiedad en tu mascota.', 5, 'NA', '60 ml'),
(129, 'Set Difusor y Repuesto para Gato', 'Feliway', 2, 'https://www.petco.com.mx/medias/126895.jpg-300ftw?context=bWFzdGVyfHJvb3R8OTA5OTB8aW1hZ2UvanBlZ3xoZTAvaGJmLzEwNDkyNjUxMTQzMTk4LzEyNjg5NS5qcGdfMzAwZnR3fGRkMzU5NGUzNTY3MDdlZDhhZWUzN2I4NTg4ODk2MzBkNmFmM2Y0YzI4ODRkMzM3ZjdiNmY4OWEzNmZmOTJhNTU', '$1,256.00', 'Set difusor y repuesto para gatos, ayuda a reducir el estrés y promueve la armonía en el hogar.', 5, 'NA', '48 ml'),
(130, 'Alimento Húmedo Gastrointestinal para Gato', 'Hills Prescription Diet', 2, 'https://www.petco.com.mx/medias/105193.jpg-300ftw?context=bWFzdGVyfHJvb3R8NTE4MjZ8aW1hZ2UvanBlZ3xoZWQvaGY4LzEwNDcxODM0NzE0MTQyLzEwNTE5My5qcGdfMzAwZnR3fGU0NGVlMTBlNDdhZWIwMTQzMzJkNTQ3MTkwMzA1ZDBjZmFjMDdjYzgzMjIxNDQ1MTg0NjkzN2FmOWExOWMwN2U', '$95.00', 'Alimento húmedo gastrointestinal para gatos. Especialmente formulado para apoyar la salud digestiva.', 5, 'NA', '155 g'),
(131, 'Alimento Seco Gastrointestinal Alto en Energía para Gato Adulto', 'Royal Canin Veterinary Diet', 2, 'https://www.petco.com.mx/medias/104827.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzkxNTl8aW1hZ2UvanBlZ3xoOGEvaDdmLzEwNTUwODA5ODIxMjE0LzEwNDgyNy5qcGdfMzAwZnR3fDJhNDA5ODY5MjFhNGQzNDk0MGYxZDNiODBmNjEzZGRjMDUzOGIyMTU3ZWE4NWQ3MjUxOGY5Njc0ZmFiMGZmOTA', '$1,586.50', 'Alimento seco alto en energía para gatos adultos. Formulado para apoyar la salud gastrointestinal.', 5, 'NA', '4 kg'),
(132, 'Shampoo Terapéutico para Perro y Gato', 'Vetriderm', 1, 'https://www.petco.com.mx/medias/300ftw-116477.jpg?context=bWFzdGVyfHJvb3R8MTg5MjJ8aW1hZ2UvanBlZ3xoZjAvaDE0LzEwODk2NTA2OTQ1NTY2LzMwMGZ0d18xMTY0NzcuanBnfDVlNjI5ZDgxN2Y2M2Q2YWJkNzQ3YmIyYzEzMzliZTM1ZjAxNTU2NzI2YmQ4YWU0MWU4NWU1MGExZWUzYTVhZWI', '$227.29', 'Shampoo terapéutico para perros y gatos. Ayuda a tratar problemas de piel y mantiene el pelaje saludable.', 5, 'NA', '350 ml'),
(133, 'Repuesto para Difusor para Gato', 'Feliway', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w2NjE5OHxpbWFnZS9qcGVnfGltYWdlcy9oZDIvaDg5LzkyMzQ3NTYzMDQ5MjYuanBnfDBkNzUzMmNjNDc1ZmE2ZWJlOGVlMWQ1ZWNjZWI1MTkwZDIwYjg5ZWZmMjIzYTc4MjcxMjM3ZDg3YzhjM2VjYmI', '$711.55', 'Repuesto para difusor Feliway Friends. Ayuda a reducir el estrés y promover la armonía entre gatos.', 5, 'NA', '48 ml'),
(134, 'Set Difusor y Repuesto con Efecto Calmante para Gato', 'Feliway', 2, 'https://www.petco.com.mx/medias/122244.jpg-300ftw?context=bWFzdGVyfHJvb3R8OTIyNzF8aW1hZ2UvanBlZ3xoYWYvaDk5LzEwNDkyNjQ2ODgzMzU4LzEyMjI0NC5qcGdfMzAwZnR3fDZiZDFmOGJjN2JhM2I4NzNkNmRmZDM1YTU1MDZjNzAxNDc5YjJkYjQ1OGU5OTA0ZDEzNzQ1MzI1YWIwODZjOTg', '$1,187.60', 'Set difusor y repuesto con efecto calmante para gatos. Ayuda a reducir el estrés y la ansiedad.', 5, 'NA', '48 ml'),
(135, 'Repuesto para Difusor para Gato', 'Feliway', 2, 'https://www.petco.com.mx/medias/122245.jpg-300ftw?context=bWFzdGVyfHJvb3R8NzUyOTd8aW1hZ2UvanBlZ3xoZTcvaDQwLzEwNDkyNjQ5MTc3MTE4LzEyMjI0NS5qcGdfMzAwZnR3fDVlNWQyNWZkZDM0MTU5MDM2MzM4ZmI1NTZhNjAyM2Y1N2M0YzllYTFkZGMwMzM3MGRmNTcxMTJhMWI2NTkxYWQ', '$683.05', 'Repuesto para difusor Feliway Classic. Ayuda a reducir el estrés y ansiedad en tu gato.', 5, 'NA', '48 ml'),
(136, 'Pipeta Antiparasitaria Interna y Externa para Gato', 'Advantage Multi', 2, 'https://www.petco.com.mx/medias/300ftw-104716.jpg?context=bWFzdGVyfHJvb3R8NzEzMDZ8aW1hZ2UvanBlZ3xoNGYvaGJlLzEwODk2NTA0OTc5NDg2LzMwMGZ0d18xMDQ3MTYuanBnfDgxZTZkMDYxMWU5MWZhZGU3N2RjMTlhZTJhNDM1MWRhMDhhYWMzZjM4NTJlMWYwZTE1ZjA5NGVmMjBkODZlNzA', '$355.54', 'Pipeta antiparasitaria interna y externa para gatos de 4 kg. Proporciona protección contra parásitos.', 5, 'NA', '4 kg'),
(137, 'Jabón Dermatológico para Perro y Gato', 'Vetriderm', 1, 'https://www.petco.com.mx/medias/107385.jpg-300ftw?context=bWFzdGVyfHJvb3R8NjM4NDh8aW1hZ2UvanBlZ3xoMTkvaDVhLzEwNDg2MzUxOTIxMTgyLzEwNzM4NS5qcGdfMzAwZnR3fGQ2MjE5NGFhY2JiOTcxMjVlMzRiYzkwZmNhNGRjNDU0NDA0NDViMTY3MTI0NjU5NjgyYWUwNmE2MjFjMWQ5ODQ', '$113.29', 'Jabón dermatológico para perros y gatos. Ayuda a tratar problemas de piel y mantiene la higiene del pelaje.', 5, 'NA', '100 g'),
(138, 'Set Arnés de Malla y Correa para Gato', 'Good2Go', 2, 'https://www.petco.com.mx/medias/125072.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDQ2NTl8aW1hZ2UvanBlZ3xoMTUvaDM0Lzk1ODg0NDg0MjgwNjIuanBnfGUyMzM2ZDRiZTg1MzFlZTVhMjQxMTZjMDgxNDk3NDExNTY3MDBmNTI2YmI1ZTg1NjBhNDlmZmNiNmRiNTlhNjg', '$224.25', 'Proporciona comodidad y seguridad durante los paseos.', 2, 'Aqua', 'NA'),
(139, 'Set Arnés de Malla y Correa para Gato', 'Good2Go', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyNjk1M3xpbWFnZS9qcGVnfGltYWdlcy9oMTYvaDgyLzkxODM1MzYzODE5ODIuanBnfDlmZmJmYzQwOTVmYjFlZjkxMmE1OGVmYzU3NGY4Mzg5MmU2MGZiMzUwZTFjMDdlNDc0ZGEyZjA1YzQ4NWQyNzU', '$224.25', 'Proporciona comodidad y seguridad durante los paseos.', 2, 'Negro', 'NA'),
(140, 'Collar con Broche de Seguridad Diseño Tartán y Moño para Gatito Color Rojo', 'Bond & Co', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wzNDEyMnxpbWFnZS9qcGVnfGltYWdlcy9oMmMvaGJkLzkwNDE0NDY4OTU2NDYuanBnfDRiOGRhN2FjNjY2MGE3YWQ4NDIwODliMTc3NTUzMmIwOGI5ZjExYTYzZWJlNTRlYmE2MmI4YjY5M2FlOGNhNjE', '$81.75', 'Collar con broche de seguridad y diseño tartán con moño en color rojo para gatitos. Elegancia y seguridad combinadas.', 2, 'Rojo', 'NA'),
(141, 'Collar con Broche de Seguridad Diseño a Cuadros y Moño para Gato', 'Bond & Co', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyNjYwM3xpbWFnZS9qcGVnfGltYWdlcy9oMjcvaDFlLzkwNDE0NDIwNzg3NTAuanBnfGEyY2Q3NGYxZmY4NTZiZjU1MjhiMDMxYmVkOGYwNzcxODNlYjc3MWM1NTI2ZWNiMmEwN2E1NDdhNDNmNzhiMmM', '$111.75', 'Collar con broche de seguridad y diseño a cuadros con moño en color negro para gatos. Elegancia y seguridad combinadas.', 2, 'Negro', 'NA'),
(142, 'Set Arnés y Correa Elástica', 'Youly', 2, 'https://www.petco.com.mx/medias/133882.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzgwMzN8aW1hZ2UvanBlZ3xoMTMvaGE5Lzk4OTc2NTQ3Nzk5MzQvMTMzODgyLmpwZ18zMDBmdHd8NmJlZTdkODk5NWY1ZGMzMTJhMDdkY2Q4NGY4NWU4NzdlMzczNzYxZmZiYTAyZDFjZWYyZmYyMzFmODA1MDU0Yw', '$224.25', 'Set de arnés y correa elástica con diseño reflectante en color negro para gatos. Proporciona seguridad y comodidad en paseos nocturnos.', 2, 'Negro', 'Chico/Mediano'),
(143, 'Collar con Broche Diseño Luna y Estrellas para Gato', 'Youly', 2, 'https://www.petco.com.mx/medias/133871.jpg-300ftw?context=bWFzdGVyfHJvb3R8MTkzOTZ8aW1hZ2UvanBlZ3xoNDAvaGY2Lzk4OTc2MzQ3OTE0NTQvMTMzODcxLmpwZ18zMDBmdHd8MjhlNWRhODA5OTdmMmMzZmIyNWE5MzkyNWNlODE1NzI3MTY3ZDMyN2M1MjI4NzAxNDk3NjM2ZjJmNTg5NzE5MQ', '$111.75', 'Collar con broche de seguridad con diseño de luna y estrellas en color azul para gatos. Añade un toque de estilo y seguridad.', 2, 'Azul', 'NA'),
(144, 'Collar con Broche de Seguridad Diseño Estrellas y Luna para Gatito', 'Bond & Co', 2, 'https://www.petco.com.mx/medias/128470.jpg-300ftw?context=bWFzdGVyfHJvb3R8NTQ3Nzl8aW1hZ2UvanBlZ3xoYjkvaDg4LzkzNjI1NDE3MDcyOTQuanBnfDIzZTFhZDE0ZGI5OThjMzQ2MDA4OTZkNTc4MDc0OGNmNDE1ZGI1OGIzMDRjMThjYzNjNTAzZWRmMjVjYjg5ZDc', '$81.75', 'Collar con broche de seguridad y diseño de estrellas y luna en color azul para gatitos. Elegancia y seguridad combinadas.', 2, 'Azul', 'NA'),
(145, 'Collar Reflejante Elástico Diseño a Rayas para Gatito', 'Bond & Co', 2, 'https://www.petco.com.mx/medias/101833.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDM4NjN8aW1hZ2UvanBlZ3xoYWQvaDFhLzk1ODg0NDIzOTg3NTAuanBnfDA4Mzc3ZDg0MTFjOGIzMTY1ZjAyZmIwOWMxNjAyYTUyYTYzOWIwM2M4YWFhNTdlMDgyMWEyYjA2YTYxZTgxNGY', '$74.25', 'Collar reflejante y elástico con diseño a rayas en color negro para gatitos. Proporciona visibilidad y seguridad en paseos nocturnos.', 2, 'Negro', 'NA'),
(146, 'Collares con Broche de Seguridad Diseño Liso y Geométrico para Gato', 'Good2Go', 2, 'https://www.petco.com.mx/medias/128481.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDAxMzh8aW1hZ2UvanBlZ3xoMDYvaGY5LzkzNjI1NDQwNjY1OTAuanBnfGQ5MmIwOThlZWJhYjZiNWMwYWFmNTFkZTE0ZTQzZWI5Yzc4NjVmMzJiYWNhMTdiYWYwODhlZGM5OWQ1ZGNlM2E', '$149.25', 'Set de collares con broche de seguridad y diseño liso y geométrico en color morado para gatos. Elegancia y seguridad combinadas.', 2, 'Morado', 'NA'),
(147, 'Collar con Broche Diseño de Terciopelo con Moño para Gatito', 'Youly', 2, 'https://www.petco.com.mx/medias/133865.jpg-300ftw?context=bWFzdGVyfHJvb3R8Mjc0NzF8aW1hZ2UvanBlZ3xoYjMvaGFhLzk4OTc2MDk3MjM5MzQvMTMzODY1LmpwZ18zMDBmdHd8ZjFmOGRjMDRmMzA2MjAwMzUwYzUzYzNmNjA4YjFmYmFiMGEwNzJiMGM2NzM0Mjc0ZjQ5NmFlN2VlMjYyOTczYQ', '$74.25', 'Collar con broche de seguridad y diseño de terciopelo con moño en color lila para gatitos. Elegancia y suavidad combinadas.', 2, 'Lila', 'NA'),
(148, 'Set Arnés y Correa Elástica y diseño reflectante para Gato', 'Youly', 2, 'https://www.petco.com.mx/medias/133883.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDQ1NDd8aW1hZ2UvanBlZ3xoNzAvaDMxLzk4OTc2NTcwNzM2OTQvMTMzODgzLmpwZ18zMDBmdHd8N2E4NDQ3MTEyODIwMTVjN2E2NDcyN2FhNjU0YmM1YzZmNzE5YTI0ODAzZGU0MTY5OGI5ODMzMGEyYmQ4MDU4MQ', '$224.25', 'Set de arnés y correa elástica con diseño reflectante en color negro para gatos. Proporciona seguridad y comodidad en paseos nocturnos.', 2, 'Negro', 'Grande/X-Grande'),
(149, 'Tenebrios Deshidratados para Reptiles Anfibios y Aves', 'Optiprot', 5, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w5MDM1NnxpbWFnZS9qcGVnfGltYWdlcy9oZWUvaDY5Lzk0NTU3MjgwNjY1OTAuanBnfGFiMGM4MzkzZWYzNjI1MjE3YjM5ZDQxNGY5M2RmNzBlYjAxOWQ3NWJhMTNmYzhhMzc2YzgwNTExMzc4Y2JlMzU', '$266.00', 'Proporciona una fuente rica de proteínas.', 3, 'NA', '125 g'),
(150, 'Maitenance Formula Alimento para Tortuga Acuática', 'Zoo Med', 5, 'https://www.petco.com.mx/medias/127164.jpg-300ftw?context=bWFzdGVyfHJvb3R8NzIzODd8aW1hZ2UvanBlZ3xoNzgvaGNkLzEwNTA4Nzk2NDI4MzE4LzEyNzE2NC5qcGdfMzAwZnR3fDE3MWJkNTdmNzg2MWFkZmQ4NWZlZjcyYjRlM2M0MDg0NzVjY2ExZGU0ZWI5ZDUxNzQyNjg2MWY3ODQ1MTBhMjU', '$512.05', 'Mantiene a tus tortugas saludables y bien alimentadas.', 3, 'NA', '1.27 kg'),
(151, 'Alimento In Care Herbívora Suplemento de Cuidados Intensivos para Animales Herbívoros', 'Emeraid', 5, 'https://www.petco.com.mx/medias/300ftw-136502.jpg?context=bWFzdGVyfHJvb3R8NjY3NTF8aW1hZ2UvanBlZ3xoM2EvaGYxLzEwNjc2MjM3NDY3Njc4LzMwMGZ0d18xMzY1MDIuanBnfDM0ZGJhZWNlYmYyNjhjZmZhYWE3MGM0ZjllMDVkMTI4M2UyZDkxYTQ3OWVkNTU3MThiNGI2YzY3YjdlM2Q4ZTM', '$645.00', 'Ayuda en la recuperación y el bienestar de tus mascotas.', 3, 'NA', '100 g'),
(152, 'Aquatic Diet Alimento Flotante para Tortugas Acuáticas', 'Mazuri', 5, 'https://www.petco.com.mx/medias/300ftw-106618.jpg?context=bWFzdGVyfHJvb3R8NjA2Mjd8aW1hZ2UvanBlZ3xoYWQvaGQyLzEwNjA2MzY5MTEyMDk0LzMwMGZ0d18xMDY2MTguanBnfGNiOThhMmY4ZDZlODQwMjE3MWZiODY4ZGMxYzI5ZjIwMTZhZDExNmEzNzFhZGI1NWUzMjU3MjUxZWM4MzJiOWE', '$304.00', 'Proporciona una dieta equilibrada y nutritiva.',  3, 'NA', '450 g'),
(153, '9 en 1 Alimento Tipo Sticks Flotantes para Tortugas Acuáticas y Reptiles', 'Azoo', 5, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w2MDAyOXxpbWFnZS9qcGVnfGltYWdlcy9oZjMvaGM2Lzk0MDAwMDcyOTUwMDYuanBnfDgxZDcyYmU1MTViM2RjODlmMzMyMTJlODFhOTYyOTUwOTYyM2RhYjc3OWU5YWIyMGVmZWIxZTkyNzIzMzJlODY', '$413.25', 'Rico en nutrientes esenciales.', 3, 'NA', '300 g'),
(154, 'Alimento para Tortuga Tortugueta Vegetal', 'Petmmal', 5, 'https://www.petco.com.mx/medias/106112.jpg-300ftw?context=bWFzdGVyfHJvb3R8OTE0ODN8aW1hZ2UvanBlZ3xoZDgvaDg2LzEwMzY2NDM2MjEyNzY2LzEwNjExMi5qcGdfMzAwZnR3fDJkMzA1MmNjYzQ4YTEwNDAwYmUyMzBhZTMwYjY5MmYwNmU0ZmE3NTViNmEzNTI5NjU2ZjQ0YmQ5NGIzYzAzZjg', '$199.50', 'Proporciona una dieta natural y equilibrada.', 3, 'NA', '500 g'),
(155, 'Reptoguard Water Acondicionador para Tortuga, 3 Piezas', 'Tetra', 5, 'https://www.petco.com.mx/medias/124295.jpg-300ftw?context=bWFzdGVyfHJvb3R8ODI4Nzd8aW1hZ2UvanBlZ3xoMTYvaDY1LzEwNTQ2OTU4OTkxMzkwLzEyNDI5NS5qcGdfMzAwZnR3fGNhNWVlMjFkMWNkNTEyMjY4NzNmMjg4MGUwZWRmNTAwY2FkMjM4YTc1YmJiMWE0N2UzYjA4ODAzNjljYmQwYzk', '$137.75', 'Mantiene el agua limpia y libre de bacterias.', 1, 'NA', 'NA'),
 (156, 'Placa Térmica', 'Petmmal', 5, 'https://www.petco.com.mx/medias/300ftw-106291.jpg?context=bWFzdGVyfHJvb3R8ODcwMDh8aW1hZ2UvanBlZ3xoMzMvaGYxLzEwNzUzMDQ2NjQyNzE4LzMwMGZ0d18xMDYyOTEuanBnfDg1OWFjY2ZhNzVmMWQxNDZiMGQ5OTZmYzVlMTkzNzhhZmUyMGNiZGFkNDc1Y2U4MzRiYTA2YTA0ZTBhZGYwNGM', '$470.25', 'Proporciona un ambiente cálido y adecuado para reptiles.', 1, 'NA', '18 x 26 cm'),
(157, 'Tronco de Madera Decorativa para Terrarios', 'Zoo Med', 5, 'https://www.petco.com.mx/medias/300ftw-115301.jpg?context=bWFzdGVyfHJvb3R8NDU2MzR8aW1hZ2UvanBlZ3xoYzgvaGQ5LzEwNjA2Mzg1MTY4NDE0LzMwMGZ0d18xMTUzMDEuanBnfDA3NzQyZTc4ZDlhNDZmNzI4ZmQwNGMyZDdlYWFiNjAwY2UwZDA0MmNjMWNiY2JmZGMzNzc3NmE5OGRjMGJjOGE', '$259.00', 'Tronco de madera decorativa para terrarios en tamaño mediano. Añade un toque natural al hábitat de tus reptiles.', 1, 'NA', '30.40 cm Largo x 25.40 cm Ancho'),
(158, 'Acondicionador Aquasafe para Reptiles', 'Tetra', 5, 'https://www.petco.com.mx/medias/106922.jpg-300ftw?context=bWFzdGVyfHJvb3R8NTYwNDB8aW1hZ2UvanBlZ3xoZWIvaDdmLzEwNTE1MzMzNDgwNDc4LzEwNjkyMi5qcGdfMzAwZnR3fDQ3YTE3ZjgzYTQwZTg3NzQzMDE2MTJkOWE0MDFiNjBjZGY3ZDA5YmI2ZjBiZTE3ZTRjOTE4OTM3OTBjYjZjOGU', '$109.25', 'Mantiene el agua en condiciones óptimas.', 1, 'NA', '100 ml'),
(159, 'Pinzas de Acero Inoxidable', 'Zoo Med', 5, 'https://www.petco.com.mx/medias/300ftw-101985.jpg?context=bWFzdGVyfHJvb3R8NTM4MjN8aW1hZ2UvanBlZ3xoMmYvaGU1LzEwNjA2MzM1MjYyNzUwLzMwMGZ0d18xMDE5ODUuanBnfDY1YWQ0MjE0OTIzNWNmY2YzODRlODkzMzgzZmU3OGIzODJhZTg5N2MyOTg5M2RlMzFlZTNhMTE1NTFlZTQ0Njc', '$189.00', 'Ideal para manipular alimentos y objetos en terrarios.',  1, 'NA', '25.4 cm'),
(160, 'Placa Térmica', 'Petmmal', 5, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyNjU0OHxpbWFnZS9naWZ8aW1hZ2VzL2gyOC9oOWIvODg0ODQ4MjMwNDAzMC5naWZ8MTNjMzFmNGI2MGU3NjBlNjg3NTVhYTJhYzA4ZWJhOWViYmNlOWYyMjA0NGQ1NjQ3ZjFhNTgyMmQ0NjcxOTQ5NQ', '$508.25', 'Proporciona un ambiente cálido y adecuado para reptiles.', 1, 'NA', '36 x 14 cm');








