INSERT INTO products (id, title, marca, fk_id_petType, image, price, description, fk_id_category, color, size) VALUES 
(41, 'Mueble Tipo Torre con Rampa', 'EveryYay', 2, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wzNTc1N3xpbWFnZS9qcGVnfGltYWdlcy9oNmIvaGU3Lzk1MzgzNjY3MzQzNjYuanBnfGMxNWVhY2E1ODBmMzUzOGMyMTc5NWVjZDQ1MGUwOTcwOWM0NzVjZTVjNjQ5OTRiODM1MTk1ZjZjNDc4Mjk2MTQ', '$1,079.40', 'Mueble para Gatito Tipo Torre con Rampa.', 4, 'Gris', 'NA'),
(42, 'Mueble Tipo Torre Con Guarida y Repisa', 'EveryYay', 2, 'https://www.petco.com.mx/medias/300ftw-142229.jpg?context=bWFzdGVyfHJvb3R8MzQ4Mjd8aW1hZ2UvanBlZ3xoMjEvaGZhLzEwNjA2NjE1NzU2ODMwLzMwMGZ0d18xNDIyMjkuanBnfGUxZmI4YzBkOTEzYmFhZTc3OWJjNTlmNDVmYTU1MmQ3OTA3YmY5N2VkZjIzYWU1MjM3ZjJlMWI4MzRkZDQ0NGQ', '$1,679.40', 'Mueble Tipo Torre con Guarida y Repisa para Gato, Beige.', 4, 'Beige', 'NA'),
(43, 'Alberca de Pelotas para Juegos', 'Marshall', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3wyNDE5MXxpbWFnZS9qcGVnfGltYWdlcy9oYTQvaDI2Lzk1MjkxNTczNTM1MDIuanBnfDFlNmYwOGZhMzU5YjJhNTU5NWM1ZGY5ZWIxMDJkNTJkY2FmYzMyZWQ2NTQyYjA0NGM3OGI2YTZlMGU5YWUzMjM', '$775.00', 'Marshall Alberca de Pelotas para Juegos Pop-n-Play.', 4, 'NA', 'NA'),
(44, 'Chew Esferas de Sauce', 'You & Me', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w2MTA4OXxpbWFnZS9qcGVnfGltYWdlcy9oZTQvaDIzLzkyMDEzNTU4MTY5OTAuanBnfGQyMjBmNWQ5MGY3ZmI5NjI4OTI1ZDJlMWQxNmI5MzEyZGYzMWYxOWI2MjcyYzhiZWNiYzcyNTFhNDQ1ZmMyODk', '$123.50', 'You & Me Chew Esferas de Sauce, 3 Piezas.', 4, 'NA', 'NA'),
(45, 'Bolas Rodadoras para Pequeñas Mascotas', 'Oxbow', 3, 'https://www.petco.com.mx/medias/133191.jpg-300ftw?context=bWFzdGVyfHJvb3R8NjI5MTV8aW1hZ2UvanBlZ3xoYjcvaDVmLzk1NzU1MzcwNDk2MzAuanBnfDcxYTU3NmQ0Y2U4MzA2NjFiZGJmMGFlYTg5ODY0OTliZDJlNzFjOGU5YzJmMzRkYTVjZThlNTkxODYwZTMyNTA', '$161.50', 'Oxbow Enriched Life Bolas Rodadoras para Pequeñas Mascotas.', 4, 'NA', 'NA'),
(46, 'Escondite Castillo', 'You & Me', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w0ODA3OXxpbWFnZS9qcGVnfGltYWdlcy9oZTIvaDQxLzkyMDEzMTk1NDI4MTQuanBnfDFlYzY0ODljZjVlMzU4ZWJhMjNiNWYxYmQxMDk5OTlmYzc3YjdjZDJkOWM0NDA1YjExODZhMGExZDIzN2ZlOTQ', '$145.00', 'You & Me Escondite Castillo, Mediano.', 4, 'NA', 'NA'),
(47, 'Túnel', 'Ware', 3, 'https://www.petco.com.mx/medias/?context=bWFzdGVyfGltYWdlc3w1MjI5MHxpbWFnZS9naWZ8aW1hZ2VzL2gwMy9oNGQvODg0ODEwMzU3MTQ4Ni5naWZ8MjYyMjhiMjJkY2U4ODY3ZTA0NjI1ZGY0YzU4N2MzMGQ2ZWE5YjVjMGZkNWQ3YzY4NzMzNzMyNzc0ODE2NzI1Nw', '$289.75', 'Ware Túnel, XX-Grande.', 4, 'NA', 'NA'),
(48, 'Microchip Para Mascotas Perros y Gatos', 'Chip Mascotas', 1, 'https://m.media-amazon.com/images/I/61RcC5iGZML._AC_SL1200_.jpg', '$850.75', '1x Microchip de 7mm con aplicador, 1 Pasaporte para mascotas, 1 Placa inteligente NFC & QR, 1 Certificado QR/Nfc, 4 Tarjetas de Identificación de microchip, 6 Etiquetas con el número del microchip, 1 Registro de microchip en plataforma de por vida.', 5, 'NA', 'NA'),
(49, 'Bebedero Mason', 'Stokes Wildbird', 4, 'https://www.petco.com.mx/medias/125017.jpg-300ftw?context=bWFzdGVyfHJvb3R8NDE4NjJ8aW1hZ2UvanBlZ3xoMmEvaGM1LzEwNTI3ODg5MTk1MDM4LzEyNTAxNy5qcGdfMzAwZnR3fDIwNzdlNjIwNjI2MGY1NmJkMTBlMGJkYTViMmJiY2E4Njg0MzJjNDIwNjdmNmNhMDVlOGJjNzJmZTcwMGFmZTQ', '$669.00', 'Un bebedero encantador con un diseño clásico de Mason Jar, perfecto para atraer colibríes.', 1, 'NA', 'NA'),
(50, 'Bebedero Amatista', 'Stokes Wildbird', 4, 'https://www.petco.com.mx/medias/125016.jpg-300ftw?context=bWFzdGVyfHJvb3R8MzY3ODV8aW1hZ2UvanBlZ3xoNTgvaDA5LzEwNTI3ODg3ODg0MzE4LzEyNTAxNi5qcGdfMzAwZnR3fGRiYWJmNjZmNDcwMjk1YjJiNzIwN2M4MjE4MDJkOTg0MjI1ZWVmYzNkMmY1OGVlYjdjZDNmZjhjY2FhYWIwYTE', '$679.00', 'Bebedero de color amatista, atractivo y diseñado específicamente para colibríes.', 1, 'Amatista', 'NA');